# schools_data.py
# Cleaned canonical school dataset for Valencia map app.
# Each record must have stable address + lat/lon (no runtime geocoding needed).

SCHOOLS = [
    {
        "name": "Imagine Montessori School (Valencia Campus)",
        "type": "Private",
        "address": "C/ Meliana, 5, Rascaña, 46019 València, Valencia, Spain",
        "lat": 39.496921686156,
        "lon": -0.37144802282001,
        "ages": "2–9 (per published listings; verify latest)",
        "curriculum": "British / Montessori (school describes Montessori; check accreditation)",
        "languages": "English-led + Spanish support (verify day-to-day split)",
        "screen_policy": "Montessori environments typically screen-light; confirm explicit 1:1 policy in writing.",
        "notes": "Use this as the canonical 'Imagine' record to avoid duplicates.",
        "sources": [
            "https://www.arquitecturacontemporanea.org/registroarca/colegio-imagine-montessori-school",
            "https://imaginemontessori.es/en/enrichment-programme-data-processing-consent-and-use-of-images/",
            "https://www.international-schools-database.com/in/valencia-spain/imagine-montessori-school-valencia",
        ],
    },
    {
        "name": "British School of Valencia (BSV)",
        "type": "Private",
        "address": "C. de les Filipines, 37, 46006 València, Valencia, Spain",
        "lat": 39.45777,
        "lon": -0.37487,
        "ages": "Early Years–Secondary (Sixth Form campus also exists; pin is for city location listed on map sources)",
        "curriculum": "British",
        "languages": "English (main) + Spanish",
        "screen_policy": "Confirm device rollout year-by-year; varies by British schools.",
        "notes": "If you want separate pins for 'Main Campus' vs 'Nexus/Sixth Form', add a 2nd record.",
        "sources": [
            "https://mapcarta.com/W78148360",
            "https://www.bsvalencia.com/bsv-main-campus/",
        ],
    },
    {
        "name": "English School Los Olivos (Primary)",
        "type": "Private",
        "address": "C/ Pino Panera, 25, 46110 Godella, Valencia, Spain",
        "lat": 39.4533997,
        "lon": -0.3931395,
        "ages": "3–18 overall (site shows separate Primary/Secondary addresses)",
        "curriculum": "British",
        "languages": "English (main) + Spanish",
        "screen_policy": "Confirm 1:1 timing; ask for policy for Infantil/Primaria in writing.",
        "notes": "Secondary site is at Av. de los Almendros, 13 (add 2nd record if you want two pins).",
        "sources": [
            "https://www.los-olivos.es/contacto/",
            "https://pg.maptons.com/p/3578443428",
        ],
    },
    {
        "name": "Deutsche Schule Valencia / Colegio Alemán",
        "type": "Private",
        "address": "Carrer de Jaume Roig, 14–16, 46010 València, Valencia, Spain",
        "lat": 39.48163,
        "lon": -0.36273,
        "ages": "Infantil–Bachillerato",
        "curriculum": "German pathway (German School Abroad; verify Abschluss options)",
        "languages": "German + Spanish (and usually English; verify by stage)",
        "screen_policy": "Confirm 1:1 timing; German schools often introduce devices later but varies by campus.",
        "notes": "This pin fixes the earlier “wrong place” issue.",
        "sources": [
            "https://mapcarta.com/W77805494",
            "https://dsvalencia.org/es/contacto/",
        ],
    },
    {
        "name": "British College La Cañada",
        "type": "Private",
        "address": "Calle 232, 110, 46182 La Cañada, Paterna, Valencia, Spain",
        "lat": 39.53544,
        "lon": -0.47602,
        "ages": "Early Years–Secondary (verify exact stages)",
        "curriculum": "British",
        "languages": "English (main) + Spanish",
        "screen_policy": "Confirm policy; many British schools move to 1:1 later in Primary/Secondary.",
        "notes": "Pin from map source.",
        "sources": [
            "https://mapcarta.com/W401915815",
        ],
    },

    # Public schools (examples already sourced; add more once we confirm exact coords)
    {
        "name": "CEIP Municipal Benimaclet",
        "type": "Public",
        "address": "C/ Arquitecte Arnau, s/n, 46020 València, Valencia, Spain",
        "lat": 39.486754,
        "lon": -0.355967,
        "ages": "Infantil–Primaria",
        "curriculum": "Spanish (Generalitat Valenciana)",
        "languages": "Spanish + Valencian (program depends on center; verify)",
        "screen_policy": "Varies by center; confirm whether any 1:1 is used in Primaria.",
        "notes": "Official registry includes coordinates.",
        "sources": [
            "https://ceice.gva.es/abc/i_guiadecentros/es/centro.asp?codi=46004040",
        ],
    },
    {
        "name": "CEIP Rodríguez Fornos",
        "type": "Public",
        "address": "C/ de la Mare de Déu de la Cabeza, 26, 46019 València, Valencia, Spain",
        "lat": 39.460596,
        "lon": -0.397015,
        "ages": "Infantil–Primaria",
        "curriculum": "Spanish (Generalitat Valenciana)",
        "languages": "Spanish + Valencian (program depends on center; verify)",
        "screen_policy": "Varies by center; confirm whether any 1:1 is used in Primaria.",
        "notes": "Coordinates from official GVA dataset extract.",
        "sources": [
            "https://aplicaciones.edu.gva.es/ocd/areacd/bd/registre.ods",
        ],
    },
]
